version: '3.8'

services:
    GUI:
        container_name: Controller
        image: controller-deploy
        privileged: true
        network_mode: host
        tty: true
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
            - './controller_entrypoint.sh:/ROS/entrypoint.sh'
        devices:
            - '/dev/ttyACM0:/dev/ttyACM0'
        environment: 
            - DISPLAY=$DISPLAY   
        entrypoint: /ROS/entrypoint.sh
